version: '3.8'

services:
  db:
    container_name: db
    image: postgres:15
    environment:
      - POSTGRES_USER=wertun
      - POSTGRES_PASSWORD=43554453
      - POSTGRES_DB=StudentsAPI

  web:
    build:
      context: ./front-end
      dockerfile: Dockerfile_front
    volumes:
      - '.:/front'
      - 'front/node_modules'
    ports:
      - '3001:3000'

  api:
    build:
      context: ./back-end
      dockerfile: Dockerfile_api
    volumes:
      - '.:/backend'
    ports:
      - '7001:7000'
    depends_on:
      - db
volumes:
  postgres_data: